### ISSUE TITLE
Issue 33 - after Swift 3

### ISSUE THREAD

**Issue by jessesquires** [SwiftWeekly/swiftweekly.github.io#57]
For Issue 33.

Tracking the remaining Swift 3 proposals to see what gets merged by the deadline:

- SE-0134: https://github.com/apple/swift/pull/3816
- SE-0129: https://github.com/apple/swift-package-manager/pull/566
- SE-0104: https://github.com/apple/swift/pull/3796
- SE-0133: https://github.com/apple/swift/pull/3809 / https://github.com/apple/swift/pull/3838
- SE-0111: https://github.com/apple/swift/pull/3837
- SE-0089: https://github.com/apple/swift/pull/3761
- SE-0042: https://github.com/apple/swift/pull/3836
- SE-0103: https://github.com/apple/swift/pull/3853
- SE-0101: https://github.com/apple/swift/pull/3854
- SE-0096: https://github.com/apple/swift/pull/3878
- SE-0068: https://github.com/apple/swift/pull/3866
- SE-0117: https://github.com/apple/swift/pull/3882

**Comment by mominul** [comment]
- [x] Merged apple/swift#3816
- [x] Merged apple/swift-package-manager#566 
- [x] Merged apple/swift#3809 / apple/swift#3838
- [x] Merged apple/swift#3837
- [x] Merged apple/swift#3761
- [ ] Open apple/swift#3836
- [x] Merged apple/swift#3853
- [x] Merged apple/swift#3854
- [x] Merged apple/swift#3878
- [ ] Closed apple/swift#3866

**Comment by jessesquires** [comment]
Thanks @mominul ! 👍 😄

**Comment by karwa** [comment]
SE-0000: apple/swift#3796 also remains open

**Comment by mominul** [comment]
@karwa SE-0000 ?

**Comment by mominul** [comment]
@karwa SE-0000 ?

**Comment by karwa** [comment]
That's what the first post calls it; it's actually SE-0104.

https://github.com/apple/swift-evolution/blob/master/proposals/0104-improved-integers.md

**Comment by mominul** [comment]
Thank you @karwa for your clarification!
